name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: print commit message
        run: echo ${{ github.event.commits[0].message }}

      - name: conditionally fail
        run: exit ${{ (contains(github.event.head_commit.message, '[fail]') && '1') || '0' }}

  after-build:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'

    steps:
      - run: echo "Yes"
