on: 
  workflow_run:
    workflows: ["CI"]
    types:
      - "completed"

jobs:
  see-what-happened:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: print event data
        run: echo "${{ toJson(github.event) }}"
